src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $project_manager;

    /**
     * @ORM\ManyToOne(targetEntity=Currency::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $currency;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="date")
     */
    private $start_date;

    /**
     * @ORM\Column(type="date")
     */
    private $end_date;

    /**
     * @ORM\ManyToOne(targetEntity=Program::class, inversedBy="projects")
     */
    private $program;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $outcome;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $created_by;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_At;

    /**
     * @ORM\OneToMany(targetEntity=ProjectVersion::class, mappedBy="project")
     */
    private $projectVersions;

    /**
     * @ORM\OneToMany(targetEntity=ProjectSponsor::class, mappedBy="project")
     */
    private $projectSponsors;

    /**
     * @ORM\OneToMany(targetEntity=ProjectResource::class, mappedBy="project")
     */
    private $projectResources;

    /**
     * @ORM\OneToMany(targetEntity=ProjectDeliverable::class, mappedBy="project")
     */
    private $projectDeliverables;

    /**
     * @ORM\OneToMany(targetEntity=ProjectMilestone::class, mappedBy="project")
     */
    private $projectMilestones;

    /**
     * @ORM\OneToMany(targetEntity=ProjectMemberHistory::class, mappedBy="project")
     */
    private $projectMemberHistories;

    /**
     * @ORM\OneToMany(targetEntity=ProjectMembers::class, mappedBy="project")
     */
    private $projectMembers;

    /**
     * @ORM\OneToMany(targetEntity=ProjectActivity::class, mappedBy="project")
     */
    private $projectActivities;

    /**
     * @ORM\OneToMany(targetEntity=ProjectCollaborationTopic::class, mappedBy="project")
     */
    private $projectCollaborationTopics;

    /**
     * @ORM\OneToMany(targetEntity=ProjectStructure::class, mappedBy="project")
     */
    private $projectStructures;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $baseline;

    /**
     * @ORM\ManyToOne(targetEntity=OrganizationUnit::class, inversedBy="projects")
     */
    private $unit;

    /**
     * @ORM\OneToMany(targetEntity=ActivityChat::class, mappedBy="project")
     */
    private $activityChats;

    /**
     * @ORM\OneToMany(targetEntity=ProjectPlanRevision::class, mappedBy="project")
     */
    private $projectPlanRevisions;

    /**
     * @ORM\OneToMany(targetEntity=ProjectPlanStatus::class, mappedBy="project")
     */
    private $projectPlanStatuses;

    /**
     * @ORM\Column(type="integer")
     */
    private $planned_value;

    /**
     * @ORM\OneToMany(targetEntity=ProjectPlanComment::class, mappedBy="project")
     */
    private $planComments;

    /**
     * @ORM\ManyToOne(targetEntity=Objective::class, inversedBy="projects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $objective;

    /**
     * @ORM\ManyToMany(targetEntity=Organization::class)
     */
    private $stakeholder;

    /**
     * @ORM\OneToMany(targetEntity=PlanModificationRequest::class, mappedBy="project")
     */
    private $planModificationRequests;

    public function __construct()
    {
        $this->projectVersions = new ArrayCollection();
        $this->projectSponsors = new ArrayCollection();
        $this->projectResources = new ArrayCollection();
        $this->projectDeliverables = new ArrayCollection();
        $this->projectMilestones = new ArrayCollection();
        $this->projectMemberHistories = new ArrayCollection();
        $this->projectMembers = new ArrayCollection();
        $this->projectActivities = new ArrayCollection();
        $this->projectCollaborationTopics = new ArrayCollection();
        $this->projectStructures = new ArrayCollection();
        $this->activityChats = new ArrayCollection();
        $this->projectPlanRevisions = new ArrayCollection();
        $this->projectPlanStatuses = new ArrayCollection();
        $this->planComments = new ArrayCollection();
        $this->stakeholder = new ArrayCollection();
        $this->planModificationRequests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getProjectManager(): ?User
    {
        return $this->project_manager;
    }

    public function setProjectManager(?User $project_manager): self
    {
        $this->project_manager = $project_manager;

        return $this;
    }

    public function getCurrency(): ?Currency
    {
        return $this->currency;
    }

    public function setCurrency(?Currency $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getProgram(): ?Program
    {
        return $this->program;
    }

    public function setProgram(?Program $program): self
    {
        $this->program = $program;

        return $this;
    }

    public function getOutcome(): ?string
    {
        return $this->outcome;
    }

    public function setOutcome(?string $outcome): self
    {
        $this->outcome = $outcome;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_At;
    }

    public function setCreatedAt(\DateTimeInterface $created_At): self
    {
        $this->created_At = $created_At;

        return $this;
    }

    /**
     * @return Collection|ProjectVersion[]
     */
    public function getProjectVersions(): Collection
    {
        return $this->projectVersions;
    }

    public function addProjectVersion(ProjectVersion $projectVersion): self
    {
        if (!$this->projectVersions->contains($projectVersion)) {
            $this->projectVersions[] = $projectVersion;
            $projectVersion->setProject($this);
        }

        return $this;
    }

    public function removeProjectVersion(ProjectVersion $projectVersion): self
    {
        if ($this->projectVersions->removeElement($projectVersion)) {
            // set the owning side to null (unless already changed)
            if ($projectVersion->getProject() === $this) {
                $projectVersion->setProject(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    /**
     * @return Collection|ProjectSponsor[]
     */
    public function getProjectSponsors(): Collection
    {
        return $this->projectSponsors;
    }

    public function addProjectSponsor(ProjectSponsor $projectSponsor): self
    {
        if (!$this->projectSponsors->contains($projectSponsor)) {
            $this->projectSponsors[] = $projectSponsor;
            $projectSponsor->setProject($this);
        }

        return $this;
    }

    public function removeProjectSponsor(ProjectSponsor $projectSponsor): self
    {
        if ($this->projectSponsors->removeElement($projectSponsor)) {
            // set the owning side to null (unless already changed)
            if ($projectSponsor->getProject() === $this) {
                $projectSponsor->setProject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ProjectResource[]
     */
    public function getProjectResources(): Collection
    {
        return $this->projectResources;
    }

    public function addProjectResource(ProjectResource $projectResource): self
    {
        if (!$this->projectResources->contains($projectResource)) {
            $this->projectResources[] = $projectResource;
            $projectResource->setProject($this);
        }

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastLogin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $confirmToken;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $created_by;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /** 
     * @ORM\ManyToMany(targetEntity="App\Entity\UserGroup", inversedBy="users")
     */
    private $userGroup;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $position;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $full_name;

    /**
     * @ORM\ManyToOne(targetEntity=OrganizationUnit::class, inversedBy="users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $unit;

    /**
     * @ORM\Column(type="string", unique=true, nullable=true)
     */
    private $apiToken;

    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function __toString()
    {
        return $this->full_name;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeInterface
    {
        return $this->lastLogin;
    }

    public function setLastLogin(?\DateTimeInterface $lastLogin): self
    {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    public function getConfirmToken(): ?string
    {
        return $this->confirmToken;
    }

    public function setConfirmToken(?string $confirmToken): self
    {
        $this->confirmToken = $confirmToken;

        return $this;
    }

    public function getCreatedBy(): ?self
    {
        return $this->created_by;
    }

    public function setCreatedBy(?self $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    /** 
     * @return Collection|UserGroup[] 
     */ 
    public function getUserGroup(): Collection
    {
        return $this->userGroup;
    }

    public function addUserGroup(UserGroup $userGroup): self
    {
        if (!$this->userGroup->contains($userGroup)) {
            $this->userGroup[] = $userGroup;
        }
        return $this;
    }

    public function removeUserGroup(UserGroup $userGroup): self
    {
        if ($this->userGroup->contains($userGroup)) {
            $this->userGroup->removeElement($userGroup);
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->full_name;
    }

    public function setFullName(string $full_name): self
    {
        $this->full_name = $full_name;

        return $this;
    }

    public function getUnit(): ?OrganizationUnit
    {
        return $this->unit;
    }

    public function setUnit(?OrganizationUnit $unit): self
    {
        $this->unit = $unit;

        return $this;
    }

    public function getApiToken(): ?string
    {
        return $this->apiToken;
    }

    public function setApiToken(?string $apiToken): self
    {
        $this->apiToken = $apiToken;

        return $this;
    }

    public function getAllFields()
    {
        return get_object_vars($this);
    }
}

templates/project/activity_progress/_form.html.twig
{{ form_start(form) }}
<div class="form-group">
	<label>{{ form_label(form.content) }}</label> {{ form_widget(form.content,{'attr':{'class':'form-control wyiswig'}}) }}
	<div class="help-block with-errors"></div>
</div>
<div class="form-group">
	<label>{{ form_label(form.file) }}</label> {{ form_widget(form.file,{'attr':{'class':'form-control'}}) }}
	<div class="help-block with-errors"></div>
</div>
<div class="row">
	<div class="form-group col-md-6">
		<label>{{ form_label(form.start_date) }}</label> {{ form_widget(form.start_date,{'attr':{'class':'form-control', "min":activity.startDate|date("Y-m-d"), "max":activity.endDate|date("Y-m-d")}}) }}
		<div class="help-block with-errors"></div>
	</div>
	<div class="form-group col-md-6">
		<label>{{ form_label(form.end_date) }}</label> {{ form_widget(form.end_date,{'attr':{'class':'form-control', "max":activity.endDate|date("Y-m-d")}}) }}
		<div class="help-block with-errors"></div>
	</div>
</div>
<div class="form-group">
	<label>{{ form_label(form.rating) }}</label> {{ form_widget(form.rating,{'attr':{'class':'form-control'}}) }}
	<div class="help-block with-errors"></div>
</div>
<div class="form-group">
	<label>{{ form_label(form.remark) }}</label> {{ form_widget(form.remark,{'attr':{'class':'form-control wyiswig'}}) }}
	<div class="help-block with-errors"></div>
</div>
{% if not button_label is defined  %}
	<button class="btn btn-info">{{ button_label|default('Save') }}</button>
	<button class="btn  btn-warning mr-3" type="reset">Reset</button>
{% else %}
	<input type="hidden" name="edit" value="{{ edit }}">
	<a href="{{ path('activity_progress_index', {'activity': activity.id, 'project': project.id }) }}" class="btn btn-primary">
		Cancel
	</a>
	<button class="btn btn-success mr-2">{{ button_label|default('Save') }}</button>
{% endif %} 
{{ form_end(form) }}

templates/project/activity_progress/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activity Progress
{% endblock %}
{% block breadcrumb %}
	<li class="breadcrumb-item">
		<a href="{{path('project_index')}}">
			{% trans %}
			Projects
			{% endtrans %}</a>
	</li>
	<li class="breadcrumb-item">
		<a href="{{path('project_show', {'id': project.id})}}">{{ project.name }}
		</a>
	</li>
	<li class="breadcrumb-item">
		<a href="{{path('project_activity_index', {'project': project.id})}}">{% trans %}
			Activity
			{% endtrans %}</a>
	</li>
	<li class="breadcrumb-item active">{% trans %}
		Progress
		{% endtrans %}</li>
{% endblock %}
{% block pagetitle %}
	{% trans %}
	Activity Progress{% endtrans %}
{% endblock %}
{% block body %}
	{% if project.status == 4 %}
	<div class="row">
		<div class="col-md-4">
			{% if is_granted("activity_progress_create") %}
				<div class="card card-info">
					<div class="card-header">
						<h3 class="card-title">
							{% if edit %}
								Edit
							{% else %}
								Add New
							{% endif %}
						</h3>
					</div>
					<div class="card-body">
						{% if edit  %}
							{% set button_label = 'Update' %}
						{% endif %} {{ include('project/activity_progress/_form.html.twig') }}
					</div>
				</div>
			{% endif %}
		</div>
		<div class="col-md-8">
			<div class="">
				<div class="row">
					<div class="col-md-12">
						<div class="timeline">
							{% for day,reports  in report_days %}
								<div class="time-label">
									<span class="bg-green">{{ day|date("d M Y") }}</span>
								</div>
								{% for report in reports %}
									<div>
										<i class="fas fa-user bg-green"></i>
										<div class="timeline-item">
											<span class="time">
												<i class="fas fa-clock"></i> {{ report.createdAt|date('h:i') }}</span>
											<h3 class="timeline-header">
												<a href="#">{{ report.createdBy.fullName }}</a>'s progress report</h3>

											<div class="timeline-body">
												<div class="row">
													<div class="col-md-4">
														<p>Activity Period: {{ report.startDate|date("M d Y") }} - {{ report.endDate|date("M d Y") }}</p>
													</div>
													<div class="col-md-8">
														<p>Rating : {{ report.rating }}</p>
													</div>
												</div>
												<p>Remark</p>
												<p>{{ report.content|raw }}
												</p>
											</div>
											<div class="timeline-footer">
												<a href="{{ asset('upload/progress/')}}{{ report.file }}" target="_blank" class="btn btn-sm btn-primary mr-2">View File</a>
												{% if is_granted("activity_progress_edit") %}
													<form class="d-inline" method="post">
														<input type="hidden" name="edit" value="{{report.id}}">
														<button class="btn btn-warning btn-sm text-white mr-2" title="Edit">
															Edit
														</button>
													</form>
												{% endif %}
												{% if is_granted("activity_progress_delete") %}
													<form method="post" class="d-inline" action="{{ path('activity_progress_delete', {'id': report.id, 'activity': activity.id, 'project': project.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
														<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ report.id) }}">
														<button class="btn btn-danger btn-sm">
															Delete
														</button>
													</form>
												{% endif %}
											</div>
										</div>
									</div>
								{% endfor %}
							{% endfor %}
							<div>
								<i class="fas fa-clock bg-gray"></i>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	{% else %}
		<div class="jumbotron jumbotron-fluid">
			<div class="container text-center">
				<i class="fas fa-7x fa-exclamation-circle text-danger mb-2"></i>
				<h1 class="display-4">Operation Not Permitted</h1>
				<p class="lead">You can not perform this operation until the project plan is approved and implementation is started.</p>
			</div>
		</div>
	{% endif %}
{% endblock %}
{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('assets/plugins/summernote/summernote-bs4.min.css') }}">
{% endblock %}
{% block javascripts %}
	<script src="{{ asset('assets/plugins/summernote/summernote-bs4.min.js') }}"></script>
	<script>
		$(function () {
$('.wyiswig').summernote({placeholder: 'Enter details here', tabsize: 2, height: 100})
})
	</script>
	<script>
	$('#activity_progress_start_date').change( function() {
		var val = $(this).val();
		$("#activity_progress_end_date").attr({
		"min" : val
		});
	});
</script>
{% endblock %}